import type { ContentItem, Feed, Interest } from './types';

export const mockInterests: Interest[] = [
  {
    id: 'quantum',
    name: 'Quantum',
    icon: 'atom',
    color: '#818cf8',
    description: 'Quantum computing, physics, and cryptography',
  },
  {
    id: 'ai',
    name: 'AI & ML',
    icon: 'brain',
    color: '#06b6d4',
    description: 'Artificial intelligence and machine learning',
  },
  {
    id: 'semantic-web',
    name: 'Semantic Web',
    icon: 'web',
    color: '#10b981',
    description: 'Linked data, ontologies, and knowledge graphs',
  },
  {
    id: 'piano',
    name: 'Piano',
    icon: 'musical-notes',
    color: '#f59e0b',
    description: 'Piano playing, theory, and composition',
  },
  {
    id: 'astronomy',
    name: 'Astronomy',
    icon: 'telescope',
    color: '#ec4899',
    description: 'Stars, galaxies, cosmology, and space exploration',
  },
  {
    id: 'growth',
    name: 'Personal Growth',
    icon: 'trending-up',
    color: '#f97316',
    description: 'Self-improvement, habits, and social skills',
  },
];

export const mockFeeds: Feed[] = [
  {
    id: 'all',
    userId: 'demo',
    name: 'All Topics',
    icon: 'apps',
    isCombined: true,
    shuffleMode: true,
    filters: mockInterests.map((i) => ({
      interestId: i.id,
      weight: 1,
    })),
  },
  {
    id: 'phd',
    userId: 'demo',
    name: 'PhD Research',
    icon: 'school',
    isCombined: true,
    shuffleMode: false,
    filters: [
      { interestId: 'quantum', levels: ['advanced', 'research'], weight: 2 },
      { interestId: 'ai', levels: ['advanced', 'research'], weight: 2 },
      { interestId: 'semantic-web', levels: ['intermediate', 'advanced'], weight: 1 },
    ],
  },
  {
    id: 'hobbies',
    userId: 'demo',
    name: 'Hobbies',
    icon: 'heart',
    isCombined: true,
    shuffleMode: true,
    filters: [
      { interestId: 'piano', weight: 1 },
      { interestId: 'astronomy', weight: 1 },
    ],
  },
];

export const mockContent: ContentItem[] = [
  {
    id: '1',
    source: 'youtube',
    sourceId: 'yt-1',
    url: 'https://youtube.com/watch?v=example1',
    title: 'Quantum Computing in 2026: What Changed Everything',
    description:
      'A deep dive into the latest breakthroughs in quantum error correction and how superconducting qubits are reaching new milestones.',
    thumbnailUrl: 'https://picsum.photos/seed/quantum1/400/600',
    mediaType: 'video',
    duration: 840,
    author: 'Quantum Science Channel',
    publishedAt: '2026-03-20T10:00:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['quantum'],
    level: 'intermediate',
    focus: 'news',
  },
  {
    id: '2',
    source: 'arxiv',
    sourceId: 'arxiv-2401.12345',
    url: 'https://arxiv.org/abs/2401.12345',
    title: 'Attention-Free Transformers for Long-Context Reasoning',
    description:
      'We propose a novel architecture that eliminates self-attention while maintaining SOTA performance on reasoning benchmarks with 100K+ context windows.',
    thumbnailUrl: 'https://picsum.photos/seed/ai1/400/600',
    mediaType: 'paper',
    author: 'Chen et al.',
    publishedAt: '2026-03-18T00:00:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['ai'],
    level: 'research',
    focus: 'theoretical',
  },
  {
    id: '3',
    source: 'youtube',
    sourceId: 'yt-3',
    url: 'https://youtube.com/watch?v=example3',
    title: 'Learn Chopin Nocturne Op.9 No.2 — Step by Step',
    description:
      'A beautiful tutorial breaking down Chopin\'s most famous nocturne into manageable sections for intermediate pianists.',
    thumbnailUrl: 'https://picsum.photos/seed/piano1/400/600',
    mediaType: 'video',
    duration: 1200,
    author: 'Piano Academy',
    publishedAt: '2026-03-15T14:00:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['piano'],
    level: 'intermediate',
    focus: 'tutorial',
  },
  {
    id: '4',
    source: 'reddit',
    sourceId: 'reddit-abc123',
    url: 'https://reddit.com/r/astrophysics/comments/abc123',
    title: 'James Webb captures high-res image of Europa\'s subsurface ocean vents',
    description:
      'New JWST data reveals thermal signatures consistent with active hydrothermal vents beneath Europa\'s ice crust, boosting hopes for extraterrestrial life.',
    thumbnailUrl: 'https://picsum.photos/seed/astro1/400/600',
    mediaType: 'discussion',
    author: 'u/astro_research_daily',
    publishedAt: '2026-03-22T08:30:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['astronomy'],
    level: 'intermediate',
    focus: 'news',
  },
  {
    id: '5',
    source: 'youtube',
    sourceId: 'yt-5',
    url: 'https://youtube.com/shorts/example5',
    title: 'RDF vs Property Graphs in 60 Seconds',
    description:
      'Quick explainer: when to use RDF triples vs property graphs for your knowledge graph.',
    thumbnailUrl: 'https://picsum.photos/seed/semweb1/400/600',
    mediaType: 'short',
    duration: 58,
    author: 'Linked Data Explained',
    publishedAt: '2026-03-21T16:00:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['semantic-web'],
    level: 'beginner',
    focus: 'tutorial',
  },
  {
    id: '6',
    source: 'hackernews',
    sourceId: 'hn-789',
    url: 'https://news.ycombinator.com/item?id=789',
    title: 'The Science of Habit Formation: What Actually Works',
    description:
      'A comprehensive analysis of habit-building research, debunking the 21-day myth and presenting evidence-based strategies for lasting change.',
    thumbnailUrl: 'https://picsum.photos/seed/growth1/400/600',
    mediaType: 'article',
    author: 'Behavioral Science Weekly',
    publishedAt: '2026-03-19T09:00:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['growth'],
    level: 'beginner',
    focus: 'applied',
  },
  {
    id: '7',
    source: 'youtube',
    sourceId: 'yt-7',
    url: 'https://youtube.com/watch?v=example7',
    title: 'Grover\'s Algorithm Visualized — Quantum Search Explained',
    description:
      'An intuitive visual walkthrough of Grover\'s search algorithm and why it provides quadratic speedup over classical search.',
    thumbnailUrl: 'https://picsum.photos/seed/quantum2/400/600',
    mediaType: 'video',
    duration: 600,
    author: 'Quantum Visuals',
    publishedAt: '2026-03-17T11:00:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['quantum'],
    level: 'intermediate',
    focus: 'tutorial',
  },
  {
    id: '8',
    source: 'devto',
    sourceId: 'devto-456',
    url: 'https://dev.to/mlops/fine-tuning-llms-2026',
    title: 'Fine-Tuning LLMs on Custom Datasets: 2026 Playbook',
    description:
      'Practical guide to LoRA, QLoRA, and full fine-tuning with the latest open-weight models. Includes benchmarks and cost comparisons.',
    thumbnailUrl: 'https://picsum.photos/seed/ai2/400/600',
    mediaType: 'article',
    author: 'MLOps Community',
    publishedAt: '2026-03-16T13:00:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['ai'],
    level: 'advanced',
    focus: 'applied',
  },
  {
    id: '9',
    source: 'youtube',
    sourceId: 'yt-9',
    url: 'https://youtube.com/shorts/example9',
    title: 'Why Does the Moon Look Bigger on the Horizon?',
    description:
      'The moon illusion explained in under a minute — it\'s not what you think!',
    thumbnailUrl: 'https://picsum.photos/seed/astro2/400/600',
    mediaType: 'short',
    duration: 45,
    author: 'Space Minute',
    publishedAt: '2026-03-20T20:00:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['astronomy'],
    level: 'beginner',
    focus: 'entertainment',
  },
  {
    id: '10',
    source: 'youtube',
    sourceId: 'yt-10',
    url: 'https://youtube.com/watch?v=example10',
    title: 'SPARQL Federated Queries — Querying the Entire Web of Data',
    description:
      'Learn how to write SPARQL queries that span multiple knowledge graphs using SERVICE clauses and federation patterns.',
    thumbnailUrl: 'https://picsum.photos/seed/semweb2/400/600',
    mediaType: 'video',
    duration: 900,
    author: 'Semantic Web Pro',
    publishedAt: '2026-03-14T10:00:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['semantic-web'],
    level: 'advanced',
    focus: 'tutorial',
  },
  {
    id: '11',
    source: 'youtube',
    sourceId: 'yt-11',
    url: 'https://youtube.com/watch?v=example11',
    title: 'How to Build Unshakeable Confidence — Backed by Science',
    description:
      'Neuroscience-based techniques for building genuine self-confidence that actually last.',
    thumbnailUrl: 'https://picsum.photos/seed/growth2/400/600',
    mediaType: 'video',
    duration: 720,
    author: 'Mind Mastery',
    publishedAt: '2026-03-21T07:00:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['growth'],
    level: 'beginner',
    focus: 'applied',
  },
  {
    id: '12',
    source: 'youtube',
    sourceId: 'yt-12',
    url: 'https://youtube.com/shorts/example12',
    title: 'Jazz Voicings Every Pianist Should Know',
    description:
      'Three essential left-hand jazz voicings demonstrated in 60 seconds.',
    thumbnailUrl: 'https://picsum.photos/seed/piano2/400/600',
    mediaType: 'short',
    duration: 55,
    author: 'Jazz Piano Quick Tips',
    publishedAt: '2026-03-22T15:00:00Z',
    fetchedAt: '2026-03-23T12:00:00Z',
    interestIds: ['piano'],
    level: 'intermediate',
    focus: 'tutorial',
  },
];
